### ISSUE TITLE
Spring-Cloud Codegen Broken due to unknown import import io.swagger.configuration.NotUndefined;

### ISSUE THREAD

**Issue by FrostbittenKing** [swagger-api/swagger-codegen-generators#1319]
Hi, since introduction of the annotation NotUndefined in swagger-codegen-generators v1.0.52, spring cloud code generation breaks, due to a new annotation io.swagger.configuration.NotUndefined that doesn't seem to exist anywhere.
Commit: 2835d9de
I can't locate the dependency where this comes from. Not via grep, not google.
I have no idea how this slipped by all tests, and randomly breaks code generators using swagger-codegen-generators.
I checked the source, and for now i can only disable it with <validationMode>legacy</validationMode> in the swagger-codegen-maven-plugin / using a command line flag, when invoking swagger-codegen cli directly.
Whats the point of this annotation, and why can't I find anything about it in any package, where this got introduced.
Google doesn't turn up squats when i try to directly search ' io.swagger.configuration.NotUndefined', there is no dependency with the package path io.swagger.configuration. At least none I could find.

Thanks.

**Comment by frantuma** [comment]
`NotNullable is a [generated annotation](https://github.com/swagger-api/swagger-codegen-generators/pull/1308/files#diff-4557f185a78fc4baa0bf9b6ea6606779ed828d51c91e786a999fa431a5e5f1dbR11) to support nullable/required combinations as detailed in https://github.com/swagger-api/swagger-codegen-generators/pull/1308/, as you mentioned used when `validationMode` is set to `strict` or `loose`.

It shouldn't create issues or errors, if you are still experiencing issues please provide the spec causing the issues along with the generator options used. Please close ticket if your problem is solved

**Comment by FrostbittenKing** [comment]
Thanks, I will check, I would assume it's a bug caused by my spec, that wasn't anticipated. I check the generated code, if I can locate the annotation there. Maybe there's  a package name mismatch.

**Comment by FrostbittenKing** [comment]
Yes, I will post this, after I cleaned it up, since it's work related.

**Comment by FrostbittenKing** [comment]
> This has been fixed in #1322 and [swagger-api/swagger-codegen#12487](https://github.com/swagger-api/swagger-codegen/pull/12487).
> 
> @FrostbittenKing please have a go with latest 3.0.64-SNAPSHOT (release will follow in 1-2 days), the issues mentioned should be fixed.

Thank you!!!, I will try when I get to it.

**Comment by FrostbittenKing** [comment]
Hi, thank you for the fix, it worked without any issues, or any additional configuration. This can be closed for now.
