### ISSUE TITLE
Spring: Regression from 2 to 3: command-line args no longer respected

### ISSUE THREAD

**Issue by davidyscott** [swagger-api/swagger-codegen-generators#438]
In swagger-codegen-2.3.1 (and, presumably, later versions of the 2.x branch) I was using `-Dmodels -DmodelDocs=false -Dapis -DapiDocs=false -DapiTests=false` to generate only the models and APIs, no docs and no tests.
In 3.0.10 these flags are not respected and it attempts to ~generate everything~ parse all of the templates, which is annoying because I use a separate process to generate docs and tests and don't want them here.  I had removed the template files that pertained to tests and docs since they were not applicable, and now I have to add them back in order for the codegen-cli to complete without errors.

**Comment by davidyscott** [comment]
As an attempt to address my problems here, I added an `--ignore-missing-templates` command-line argument.  I would submit a PR, but I am somewhat stuck on the circular dependency between this repo and the main `swagger-codegen` repo.

**Comment by frantuma** [comment]
Thanks for reporting this! the issue has been fixed in swagger-api/swagger-codegen/pull/9657, which enable system properties for docs and tests, provided similarly to what done in 2.x version, e.g.

`java -DmodelTests=false -DmodelDocs=false -DapiTests=false -DapiDocs=false -Dapis -Dmodels -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate ...`

or (using `-D` program option)

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate    -i <spec>    -l <lang>    -o <outdir> -D 'modelTests=false,modelDocs=false,apiTests=false,apiDocs=false,apis=,models='`

Regarding the build, if you are starting from `3.0.0` branch of swagger-codegen and `master` branch of generators, building generators (`mvn clean install`) is sufficient to have it used by latest swagger-codegen

**Comment by davidyscott** [comment]
Thank you!!
